---
driver:
  name: ec2


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>

  region: eu-west-1
  
  instance_type: t2.micro
  subnet_id: subnet-0e9b6138ff1ce18f2
  aws_ssh_key_id: DevOpsStudents2020
  associate_public_ip: true
  
transport:
  ssh_key: ~/.ssh/DevOpsStudents2020.pem

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[node::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
